import path from "node:path";
import { legacyStorageRoot } from "./legacyStorageConfig.js";

function folder({
  id,
  label,
  relativePath,
  category,
  purpose,
  required = false,
  serviceHints = [],
}) {
  return {
    id,
    label,
    relativePath,
    category,
    purpose,
    required,
    serviceHints,
  };
}

const FOLDERS = [
  folder({
    id: "entrada",
    label: "Entrada",
    relativePath: "entrada",
    category: "entrada",
    purpose: "Raiz das caixas de chegada da Ash.",
    required: true,
    serviceHints: ["samba"],
  }),
  folder({
    id: "entrada-uploads",
    label: "Uploads",
    relativePath: "entrada/uploads",
    category: "entrada",
    purpose: "Caixa futura para uploads recebidos pela Héstia.",
    required: true,
  }),
  folder({
    id: "entrada-dispositivos",
    label: "Dispositivos",
    relativePath: "entrada/dispositivos",
    category: "entrada",
    purpose:
      "Arquivos vindos de celular, notebook, pendrive, HD externo, TV Box ou outro dispositivo.",
    required: true,
    serviceHints: ["samba"],
  }),
  folder({
    id: "entrada-manual",
    label: "Manual",
    relativePath: "entrada/manual",
    category: "entrada",
    purpose: "Caixa de chegada manual para arquivos brutos.",
    required: true,
  }),
  folder({
    id: "entrada-revisar",
    label: "Revisar",
    relativePath: "entrada/revisar",
    category: "entrada",
    purpose: "Arquivos desconhecidos que precisam de revisão humana.",
    required: true,
  }),
  folder({
    id: "codice-pdf",
    label: "PDF",
    relativePath: "codice/pdf",
    category: "codice",
    purpose: "Documentos e livros em PDF.",
  }),
  folder({
    id: "codice-epub",
    label: "EPUB",
    relativePath: "codice/epub",
    category: "codice",
    purpose: "Livros em formato EPUB.",
  }),
  folder({
    id: "codice-txt",
    label: "Textos",
    relativePath: "codice/txt",
    category: "codice",
    purpose: "Livros e documentos brutos em TXT.",
  }),
  folder({
    id: "codice-fichamentos",
    label: "Fichamentos",
    relativePath: "codice/fichamentos",
    category: "codice",
    purpose: "Notas e fichamentos em texto/markdown.",
  }),
  folder({
    id: "midia-videos",
    label: "Vídeos",
    relativePath: "midia/videos",
    category: "midia",
    purpose: "Vídeos locais servidos por Jellyfin e acessíveis via Samba.",
    required: true,
    serviceHints: ["jellyfin", "samba"],
  }),
  folder({
    id: "midia-audio",
    label: "Áudio",
    relativePath: "midia/audio",
    category: "midia",
    purpose: "Áudio local servido por Jellyfin e acessível via Samba.",
    serviceHints: ["jellyfin", "samba"],
  }),
  folder({
    id: "midia-imagens",
    label: "Imagens",
    relativePath: "midia/imagens",
    category: "midia",
    purpose: "Imagens e fotos locais.",
    serviceHints: ["jellyfin", "samba"],
  }),
  folder({
    id: "arquivos",
    label: "Arquivos",
    relativePath: "arquivos",
    category: "arquivos",
    purpose: "Documentos diversos sem categoria de mídia/códice.",
    serviceHints: ["samba"],
  }),
  folder({
    id: "documentos-textos",
    label: "Textos",
    relativePath: "documentos/textos",
    category: "documentos",
    purpose: "Documentos de texto editáveis.",
    serviceHints: ["samba"],
  }),
  folder({
    id: "documentos-planilhas",
    label: "Planilhas",
    relativePath: "documentos/planilhas",
    category: "documentos",
    purpose: "Planilhas locais.",
    serviceHints: ["samba"],
  }),
  folder({
    id: "documentos-apresentacoes",
    label: "Apresentações",
    relativePath: "documentos/apresentacoes",
    category: "documentos",
    purpose: "Apresentações locais.",
    serviceHints: ["samba"],
  }),
  folder({
    id: "arquivos-compactados",
    label: "Compactados",
    relativePath: "arquivos/compactados",
    category: "arquivos",
    purpose: "Arquivos compactados (zip/rar/7z).",
    serviceHints: ["samba"],
  }),
  folder({
    id: "codice-kindle",
    label: "Kindle",
    relativePath: "codice/kindle",
    category: "codice",
    purpose: "Livros no formato do Kindle.",
  }),
  folder({
    id: "codice-quadrinhos",
    label: "Quadrinhos",
    relativePath: "codice/quadrinhos",
    category: "codice",
    purpose: "Quadrinhos e mangás.",
  }),
  folder({
    id: "documentos-notas-fiscais",
    label: "Notas Fiscais",
    relativePath: "documentos/notas_fiscais",
    category: "documentos",
    purpose: "XML de Notas Fiscais e recibos.",
  }),
  folder({
    id: "design-fontes",
    label: "Fontes",
    relativePath: "design/fontes",
    category: "design",
    purpose: "Arquivos de fontes tipográficas.",
  }),
  folder({
    id: "midia-fotografia-raw",
    label: "Fotografia RAW",
    relativePath: "midia/fotografia_raw",
    category: "midia",
    purpose: "Fotos cruas de câmeras (RAW).",
    serviceHints: ["samba"],
  }),
  folder({
    id: "design-3d",
    label: "Projetos 3D",
    relativePath: "design/3d",
    category: "design",
    purpose: "Modelos 3D e arquivos para impressão.",
  }),
  folder({
    id: "arquivos-bancos-de-dados",
    label: "Bancos de Dados",
    relativePath: "arquivos/bancos_de_dados",
    category: "arquivos",
    purpose: "Dumps locais e arquivos de banco de dados.",
  }),
  folder({
    id: "ash-planos",
    label: "Planos",
    relativePath: "ash/planos",
    category: "ash",
    purpose: "Planos da Ash.",
    required: true,
  }),
  folder({
    id: "ash-runs",
    label: "Runs",
    relativePath: "ash/runs",
    category: "ash",
    purpose: "Execuções da Ash.",
    required: true,
  }),
  folder({
    id: "ash-quarentena",
    label: "Quarentena",
    relativePath: "ash/quarentena",
    category: "ash",
    purpose: "Executáveis, scripts e pacotes separados para revisão.",
    required: true,
  }),
  folder({
    id: "ash-ignorados",
    label: "Ignorados",
    relativePath: "ash/ignorados",
    category: "ash",
    purpose: "Referência para itens ignorados pela Ash.",
    required: true,
  }),
  folder({
    id: "backups",
    label: "Backups",
    relativePath: "backups",
    category: "backups",
    purpose: "Backups locais do usuário (fora do dataDir interno da Chama Local).",
    required: true,
  }),
  folder({
    id: "modelos",
    label: "Modelos",
    relativePath: "modelos",
    category: "modelos",
    purpose: "Modelos e templates locais do usuário.",
  }),
  folder({
    id: "logs",
    label: "Logs",
    relativePath: "logs",
    category: "logs",
    purpose: "Logs locais do usuário (fora do dataDir interno da Chama Local).",
    required: true,
  }),
  folder({
    id: "snapshots",
    label: "Snapshots",
    relativePath: "snapshots",
    category: "snapshots",
    purpose: "Snapshots locais do usuário (fora do dataDir interno da Chama Local).",
    required: true,
  }),
];

export function getStorageModel(storagePath = legacyStorageRoot()) {
  const root = storagePath;
  const mappedFolders = FOLDERS.map((f) => ({
    ...f,
    absolutePath: path.join(root, f.relativePath),
  }));
  return { root, folders: mappedFolders };
}
