/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationRouteImport } from './routes/_station'
import { Route as StationIndexRouteImport } from './routes/_station.index'
import { Route as StationSistemaRouteImport } from './routes/_station.sistema'
import { Route as StationServicosRouteImport } from './routes/_station.servicos'
import { Route as StationLogsRouteImport } from './routes/_station.logs'
import { Route as StationHistoricoRouteImport } from './routes/_station.historico'
import { Route as StationEndpointsRouteImport } from './routes/_station.endpoints'
import { Route as StationConfigRouteImport } from './routes/_station.config'

const StationRoute = StationRouteImport.update({
  id: '/_station',
  getParentRoute: () => rootRouteImport,
} as any)
const StationIndexRoute = StationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StationRoute,
} as any)
const StationSistemaRoute = StationSistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => StationRoute,
} as any)
const StationServicosRoute = StationServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => StationRoute,
} as any)
const StationLogsRoute = StationLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => StationRoute,
} as any)
const StationHistoricoRoute = StationHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => StationRoute,
} as any)
const StationEndpointsRoute = StationEndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => StationRoute,
} as any)
const StationConfigRoute = StationConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => StationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StationIndexRoute
  '/config': typeof StationConfigRoute
  '/endpoints': typeof StationEndpointsRoute
  '/historico': typeof StationHistoricoRoute
  '/logs': typeof StationLogsRoute
  '/servicos': typeof StationServicosRoute
  '/sistema': typeof StationSistemaRoute
}
export interface FileRoutesByTo {
  '/config': typeof StationConfigRoute
  '/endpoints': typeof StationEndpointsRoute
  '/historico': typeof StationHistoricoRoute
  '/logs': typeof StationLogsRoute
  '/servicos': typeof StationServicosRoute
  '/sistema': typeof StationSistemaRoute
  '/': typeof StationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_station': typeof StationRouteWithChildren
  '/_station/config': typeof StationConfigRoute
  '/_station/endpoints': typeof StationEndpointsRoute
  '/_station/historico': typeof StationHistoricoRoute
  '/_station/logs': typeof StationLogsRoute
  '/_station/servicos': typeof StationServicosRoute
  '/_station/sistema': typeof StationSistemaRoute
  '/_station/': typeof StationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/endpoints'
    | '/historico'
    | '/logs'
    | '/servicos'
    | '/sistema'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/config'
    | '/endpoints'
    | '/historico'
    | '/logs'
    | '/servicos'
    | '/sistema'
    | '/'
  id:
    | '__root__'
    | '/_station'
    | '/_station/config'
    | '/_station/endpoints'
    | '/_station/historico'
    | '/_station/logs'
    | '/_station/servicos'
    | '/_station/sistema'
    | '/_station/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StationRoute: typeof StationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_station': {
      id: '/_station'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_station/': {
      id: '/_station/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StationIndexRouteImport
      parentRoute: typeof StationRoute
    }
    '/_station/sistema': {
      id: '/_station/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof StationSistemaRouteImport
      parentRoute: typeof StationRoute
    }
    '/_station/servicos': {
      id: '/_station/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof StationServicosRouteImport
      parentRoute: typeof StationRoute
    }
    '/_station/logs': {
      id: '/_station/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof StationLogsRouteImport
      parentRoute: typeof StationRoute
    }
    '/_station/historico': {
      id: '/_station/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof StationHistoricoRouteImport
      parentRoute: typeof StationRoute
    }
    '/_station/endpoints': {
      id: '/_station/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof StationEndpointsRouteImport
      parentRoute: typeof StationRoute
    }
    '/_station/config': {
      id: '/_station/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof StationConfigRouteImport
      parentRoute: typeof StationRoute
    }
  }
}

interface StationRouteChildren {
  StationConfigRoute: typeof StationConfigRoute
  StationEndpointsRoute: typeof StationEndpointsRoute
  StationHistoricoRoute: typeof StationHistoricoRoute
  StationLogsRoute: typeof StationLogsRoute
  StationServicosRoute: typeof StationServicosRoute
  StationSistemaRoute: typeof StationSistemaRoute
  StationIndexRoute: typeof StationIndexRoute
}

const StationRouteChildren: StationRouteChildren = {
  StationConfigRoute: StationConfigRoute,
  StationEndpointsRoute: StationEndpointsRoute,
  StationHistoricoRoute: StationHistoricoRoute,
  StationLogsRoute: StationLogsRoute,
  StationServicosRoute: StationServicosRoute,
  StationSistemaRoute: StationSistemaRoute,
  StationIndexRoute: StationIndexRoute,
}

const StationRouteWithChildren =
  StationRoute._addFileChildren(StationRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StationRoute: StationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
