/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationRouteImport } from './routes/_station'
import { Route as StationIndexRouteImport } from './routes/_station.index'
import { Route as StationStorageRouteImport } from './routes/_station.storage'
import { Route as StationLogsRouteImport } from './routes/_station.logs'
import { Route as StationEndpointsRouteImport } from './routes/_station.endpoints'
import { Route as StationConfigRouteImport } from './routes/_station.config'

const StationRoute = StationRouteImport.update({
  id: '/_station',
  getParentRoute: () => rootRouteImport,
} as any)
const StationIndexRoute = StationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StationRoute,
} as any)
const StationStorageRoute = StationStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => StationRoute,
} as any)
const StationLogsRoute = StationLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => StationRoute,
} as any)
const StationEndpointsRoute = StationEndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => StationRoute,
} as any)
const StationConfigRoute = StationConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => StationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StationIndexRoute
  '/config': typeof StationConfigRoute
  '/endpoints': typeof StationEndpointsRoute
  '/logs': typeof StationLogsRoute
  '/storage': typeof StationStorageRoute
}
export interface FileRoutesByTo {
  '/config': typeof StationConfigRoute
  '/endpoints': typeof StationEndpointsRoute
  '/logs': typeof StationLogsRoute
  '/storage': typeof StationStorageRoute
  '/': typeof StationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_station': typeof StationRouteWithChildren
  '/_station/config': typeof StationConfigRoute
  '/_station/endpoints': typeof StationEndpointsRoute
  '/_station/logs': typeof StationLogsRoute
  '/_station/storage': typeof StationStorageRoute
  '/_station/': typeof StationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/config' | '/endpoints' | '/logs' | '/storage'
  fileRoutesByTo: FileRoutesByTo
  to: '/config' | '/endpoints' | '/logs' | '/storage' | '/'
  id:
    | '__root__'
    | '/_station'
    | '/_station/config'
    | '/_station/endpoints'
    | '/_station/logs'
    | '/_station/storage'
    | '/_station/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StationRoute: typeof StationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_station': {
      id: '/_station'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_station/': {
      id: '/_station/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StationIndexRouteImport
      parentRoute: typeof StationRoute
    }
    '/_station/storage': {
      id: '/_station/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StationStorageRouteImport
      parentRoute: typeof StationRoute
    }
    '/_station/logs': {
      id: '/_station/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof StationLogsRouteImport
      parentRoute: typeof StationRoute
    }
    '/_station/endpoints': {
      id: '/_station/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof StationEndpointsRouteImport
      parentRoute: typeof StationRoute
    }
    '/_station/config': {
      id: '/_station/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof StationConfigRouteImport
      parentRoute: typeof StationRoute
    }
  }
}

interface StationRouteChildren {
  StationConfigRoute: typeof StationConfigRoute
  StationEndpointsRoute: typeof StationEndpointsRoute
  StationLogsRoute: typeof StationLogsRoute
  StationStorageRoute: typeof StationStorageRoute
  StationIndexRoute: typeof StationIndexRoute
}

const StationRouteChildren: StationRouteChildren = {
  StationConfigRoute: StationConfigRoute,
  StationEndpointsRoute: StationEndpointsRoute,
  StationLogsRoute: StationLogsRoute,
  StationStorageRoute: StationStorageRoute,
  StationIndexRoute: StationIndexRoute,
}

const StationRouteWithChildren =
  StationRoute._addFileChildren(StationRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StationRoute: StationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
