/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationRouteImport } from './routes/_station'
import { Route as StationIndexRouteImport } from './routes/_station.index'

const StationRoute = StationRouteImport.update({
  id: '/_station',
  getParentRoute: () => rootRouteImport,
} as any)
const StationIndexRoute = StationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof StationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_station': typeof StationRouteWithChildren
  '/_station/': typeof StationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_station' | '/_station/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StationRoute: typeof StationRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_station': {
      id: '/_station'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_station/': {
      id: '/_station/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StationIndexRouteImport
      parentRoute: typeof StationRoute
    }
  }
}

interface StationRouteChildren {
  StationIndexRoute: typeof StationIndexRoute
}

const StationRouteChildren: StationRouteChildren = {
  StationIndexRoute: StationIndexRoute,
}

const StationRouteWithChildren =
  StationRoute._addFileChildren(StationRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StationRoute: StationRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
